polling/urls.py
from django.urls import path
from . import views

app_name= 'polling'

#urlpatterns = [
#    path('',views.index, name='index'),
#    path('<int:question_id>/',views.detail, name='detail'),
#    path('<int:question_id>/vote/',views.vote, name='vote'),
#    path('<int:question_id>/results/',views.results, name='results'),
#]

urlpatterns[
   path('',views.IndexView.as_view(), name='index'),
   path('<int:pk>/',views.DetailView.as_view(), name='detail'),
   path('<int:question_id>/vote/',views.votes, name='vote'),
   path('<int:pk>/results/',views.ResultsView.as_view(), name='results'), 
]

polls-app/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

polls_app/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('polling/',include('polling.urls')),
]

polling/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_txt = models.CharField(max_length=200)
    pub_date= models.DateTimeField('date published')

    def __str__(self):
        return self.question_txt

class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete= models.CASCADE)
    choice_txt = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_txt

polling/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Question,Choice
from django.urls import reverse
from django.views import generic

#def index(request):
#    qustn_list = Question.objects.order_by("-pub_date")
#    return render(request,'polling/index.html',{'qustn_list':qustn_list})

class IndexView(generic.ListView):
    template_name = 'polling/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]
    
#def detail(request, question_id):
#    q= get_object_or_404(Question, pk=question_id)
 #   return render(request,'polling/detail.html',{'q':q})

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polling/detail.html'
    
def vote(request,question_id):
    q = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice= q.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polling/detail.html', {'q':q, 'error_msg': "you didn't select a choice"})
    else:
        selected_choice.votes+=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polling:results', args=(q.id,)))

#def results(request,question_id):
  #  q = get_object_or_404(Question, pk=question_id)
  #  return render(request, 'polling/result.html', {'q': q})

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polling/result.html'

polling/templates/polling/detail.html
<h2>{{ q.question_txt}}</h2>
{% if error_msg %}
<p><strong>{{ error_msg }}</strong></p>
{% endif %}

<form action="{% url 'polling:vote' q.id %}" method="post">
    {% csrf_token %}
    {% for choice in q.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
        <label for="choice{{ forloop.counter }}">{{ choice.choice_txt }}</label><br/>
    {% endfor %}
    <input type="submit" value="VOTE" />
</form>

polling/templates/polling/index.html
<h1>Welcome to polling</h1>
{% if qustn_list %}
<ul>
    {% for question in qustn_list %}
    <li>
        <a href="{% url 'polling: detail' question.id %}">{{question.question_txt}}<br><br></a>
    </li>{% endfor %}
</ul>
{% else %}
    <p>No polling available</p>
{% endif %}

polling/templates/polling/result.html
<h2>{{q.question_txt}}</h2>

<ul>
    {% for choice in q.choice_set.all %}
    <li>
        {{choice.choice_txt}} -- {{choice.votes}} vote{{choice.votes|pluralize}}
    </li>
    {% endfor %}
</ul>

<a href="{% url 'polling:detail' q.id %}">Vote again?</a>